name: AITA-Golang

on:
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    outputs:
      title: ${{ steps.AITA.outputs.title }}
      body: ${{ steps.AITA.outputs.body }}
      url: ${{ steps.AITA.outputs.url }}

    steps:
      - uses: actions/checkout@v3

      #golang run to edit my demoData.json
      - name: Golang setup
        uses: actions/setup-go@v4
        with:
          go-version: stable
          check-latest: true
          # cache-dependency-path: ./src/go_files/question-builder/go.sum
      - name: generate AITA post

        id: AITA
        run: go run .
  post:
    needs:
      - build
    name: post
    runs-on: ubuntu-latest
    steps:
      - name: post to Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          title: ${{ needs.build.outputs.title}}
          description: testing more
          url: https://github.com/JeremyC3/aita-bot/actions/runs/7805027998/job/21288299921
          username: AITA-Bot
